# Use the official Node.js image as the base image
FROM node:22.14.0 AS base

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml prisma ./
COPY .dockerignore .

# Install dependencies
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Copy the rest of the application code, excluding node_modules
COPY . .

# Production build stage
FROM base AS production
RUN pnpm run build

# Expose the port the app runs on
EXPOSE 3000

# Default to development mode
CMD ["pnpm", "dev"]