import { Provider } from '@/components/providers';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Monda, Urbanist } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-urbanist',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const monda = Monda({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-monda',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${monda.variable} ${urbanist.variable} antialiased`}
      >
        <Provider>
          <div className='flex flex-col min-h-screen'>
            <main className='flex-grow'>{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
