import type { Metadata } from "next";
import { EdgeStoreProvider } from '../lib/edgestore';
import { Geist, Geist_Mono } from "next/font/google";
import { Monda } from "next/font/google"; // Add this import
import "./globals.css";
import { Provider } from "@/components/providers";
import { Urbanist } from "next/font/google"; // Urbanist font import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-urbanist",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




// Add Monda font configuration
const monda = Monda({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-monda",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${monda.variable} ${urbanist.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}